FROM node:16.14.2-alpine3.15 AS build

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install --quiet

# Bundle app source
COPY . .

# Build app
RUN npm run build

#---------------------------------

FROM nginx:1.21.6-alpine

# Remove default files
RUN rm -rf /usr/share/nginx/html/*
# COPY nginx.conf  /etc/nginx/nginx.conf

# Copy app in container
COPY --from=build /usr/src/app/dist/put3/ /usr/share/nginx/html

EXPOSE 80
