export enum CursorStyle {
  Crosshair = 'crosshair',
  Default = 'default',
  Help = 'help',
  Move = 'move',
  Grab = 'grab',
  Grabbing = 'grabbing',
  Pointer = 'pointer',
  Text = 'text',
  VerticalText = 'vertical-text',
  Progress = 'progress',
  Wait = 'wait',
  None = 'none',
  ZoomIn = 'zoom-in',
  ZoomOut = 'zoom-out',
  NotAllowed = 'not-allowed',
  ColResize = 'col-resize',
  RowResize = 'row-resize',
  EResize = 'e-resize',
  NEResize = 'ne-resize',
  NWResize = 'nw-resize',
  NResize = 'n-resize',
  SEResize = 'se-resize',
  SWResize = 'sw-resize',
  SResize = 's-resize',
  WResize = 'w-resize',
}
