FROM node:16-alpine

# Create app directory
WORKDIR /home/node/app

# Install app dependencies
COPY package*.json ./
RUN npm ci --quiet

# Bundle app source
COPY . .

# Build app
RUN npm run build

# Expose port
EXPOSE 3000

# Run app
ENV NODE_ENV=production
CMD ["npm", "run", "start:prod"]
